k8s_namespace: "default"

charts:
  - name: "cnpg"
    chart: "cloudnative-pg"
    version: "0.23.0 "
    repo: "https://cloudnative-pg.github.io/charts"
    values_template: "cnpg-values.yaml.j2"
  - name: "rook-ceph"
    chart: "rook-ceph"
    version: "1.16.2"
    repo: "https://charts.rook.io/release"
    values_template: "rook-ceph-values.yaml.j2"
  - name: "prometheus"
    chart: "kube-prometheus-stack"
    version: "68.3.0"
    repo: "https://prometheus-community.github.io/helm-charts"
    values_template: "prometheus-values.yaml.j2"
  - name: "istio"
    chart: "istiod"
    version: "1.24.2"
    repo: "https://istio-release.storage.googleapis.com/charts"
    values_template: "istio-values.yaml.j2"
