- name: Kubernetes Deployment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy Kubernetes components
      include_tasks: tasks/deploy.yaml

    - name: Set up ArgoCD
      include_tasks: tasks/argocd.yaml

    - name: Verify deployments
      include_tasks: tasks/verify.yaml
